// @ts-check
// Docusaurus configuration for the latex-snippets showcase.
// Snippet pages under docs/snippets/*.mdx are GENERATED by
// scripts/build-snippets.mjs — run `npm run build:snippets` before building.

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "LaTeX Snippets",
  tagline: "A runnable showcase of LaTeX packages — a modern complement to The LaTeX Companion",

  url: "https://latextemplates.github.io",
  baseUrl: "/latex-snippets/",
  organizationName: "latextemplates",
  projectName: "latex-snippets",
  onBrokenLinks: "warn",

  i18n: { defaultLocale: "en", locales: ["en", "de"] },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: "/",
          sidebarPath: "./sidebars.js",
          // No "Edit this page" link: snippet pages are generated, not authored.
        },
        blog: false,
        theme: { customCss: ["./src/css/custom.css", "./src/css/snippet.css"] },
      }),
    ],
  ],

  themeConfig: {
    // Prism doesn't bundle LaTeX by default; load it so ```latex blocks are
    // syntax-highlighted.
    prism: {
      additionalLanguages: ["latex"],
    },
    navbar: {
      title: "LaTeX Snippets",
      items: [
        { type: "docSidebar", sidebarId: "snippetsSidebar", label: "Snippets" },
        { type: "localeDropdown", position: "right" },
        {
          href: "https://github.com/latextemplates/generator-latex-template",
          label: "Generator",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Project",
          items: [
            { label: "Generator (source of truth)", href: "https://github.com/latextemplates/generator-latex-template" },
            { label: "The LaTeX Companion", href: "https://www.latex-project.org/help/books/" },
          ],
        },
      ],
    },
  },
};

export default config;
