// @ts-check
// Docusaurus configuration for the latex-snippets showcase.
// Snippet pages under docs/snippets/*.mdx are GENERATED by
// scripts/build-snippets.mjs — run `npm run build:snippets` before building.

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "LaTeX Snippets",
  tagline: "A runnable showcase of LaTeX packages — a modern complement to The LaTeX Companion",

  url: "https://latextemplates.github.io",
  baseUrl: "/latex-snippets/",
  organizationName: "latextemplates",
  projectName: "latex-snippets",
  onBrokenLinks: "warn",

  i18n: { defaultLocale: "en", locales: ["en", "de"] },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: "/",
          sidebarPath: "./sidebars.js",
          // Expand all categories by default so the whole catalog is visible
          // at a glance (categories can still be collapsed individually).
          sidebarCollapsed: false,
          // No "Edit this page" link: snippet pages are generated, not authored.
        },
        blog: false,
        theme: { customCss: ["./src/css/custom.css", "./src/css/snippet.css"] },
      }),
    ],
  ],

  themeConfig: {
    // Prism doesn't bundle LaTeX by default; load it so ```latex blocks are
    // syntax-highlighted.
    prism: {
      additionalLanguages: ["latex"],
    },
    navbar: {
      title: "LaTeX Snippets",
      items: [
        { type: "docSidebar", sidebarId: "snippetsSidebar", label: "Snippets" },
        { type: "localeDropdown", position: "right" },
        {
          href: "https://github.com/latextemplates/generator-latex-template",
          label: "Generator",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      // Simple (flat) footer — no column header. Generator lives in the navbar.
      links: [
        {
          label: "latex-snippets on GitHub",
          href: "https://github.com/latextemplates/latex-snippets",
        },
        {
          label: "The LaTeX Companion",
          href: "https://www.latex-project.org/help/books/",
        },
      ],
      // Interim privacy notice. This site sets no cookies and uses no analytics;
      // hosting (e.g. server-log/IP processing) is covered by GitHub. A full
      // Impressum / Datenschutzerklärung is still recommended.
      copyright:
        'Hosted on GitHub Pages — no cookies or analytics are used by this site. ' +
        'See the <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noreferrer">GitHub Privacy Statement</a> for hosting data.',
    },
  },
};

export default config;
