// Sidebar for the generated snippet pages. The `snippets/` items are produced
// by scripts/build-snippets.mjs; autogenerated so new snippets appear without
// editing this file.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  snippetsSidebar: [
    "intro",
    {
      type: "category",
      label: "Snippets",
      link: { type: "generated-index", title: "LaTeX Snippets" },
      items: [{ type: "autogenerated", dirName: "snippets" }],
    },
  ],
};

export default sidebars;
