// Sidebar for the generated snippet pages. The `snippets/` items are produced
// by scripts/build-snippets.mjs; autogenerated so new snippets appear without
// editing this file.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  snippetsSidebar: [
    "intro",
    // The feature categories under docs/snippets/<category>/ become top-level
    // sidebar groups (Source Code, Comments & TODOs, …), each with one page per
    // package. Order/labels come from the generated _category_.json files.
    { type: "autogenerated", dirName: "snippets" },
  ],
};

export default sidebars;
